Test TestError
 "Выполнить подавив исключение"
 ( ERROR 'Сообщение' )
; // TestError

TestError